marer/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

from marer.views import auth
from marer.views import cabinet
from marer.views import issue
from marer.views import rest
from marer.views import process_docs

urlpatterns = [
    url(r'^$', auth.LoginView.as_view(), name='index'),
    url(r'^login$', auth.LoginView.as_view(), name='login'),
    url(r'^login_sign$', auth.LoginSignView.as_view(), name='login_sign'),
    url(r'^logout$', auth.LogoutView.as_view(), name='logout'),
    url(r'^register$', auth.RegisterView.as_view(), name='register'),
    url(r'^password_reset/request$', auth.PasswordResetRequestView.as_view(), name='password_reset_request'),
    url(r'^password_reset/reset$', auth.PasswordResetResetView.as_view(), name='password_reset_reset'),

    url(r'^cabinet/requests$', cabinet.CabinetRequestsView.as_view(), name='cabinet_requests'),
    url(r'^cabinet/organizations$', cabinet.CabinetOrganizationsView.as_view(), name='cabinet_organizations'),
    url(r'^cabinet/profile$', cabinet.CabinetProfileView.as_view(), name='cabinet_profile'),
    url(r'^manager$', cabinet.CabinetManagerView.as_view(), name='cabinet_manager'),

    url(r'^cabinet/requests/new$', issue.IssueRegisteringView.as_view(), name='issue_new'),
    url(r'^cabinet/requests/(?P<iid>\d+)$', issue.IssueRedirectView.as_view(), name='cabinet_request'),

    url(r'^cabinet/requests/(?P<iid>\d+)/reg$', issue.IssueRegisteringView.as_view(), name='issue_registering'),
    url(r'^cabinet/requests/(?P<iid>\d+)/srv$', issue.IssueSurveyView.as_view(), name='issue_survey'),
    url(r'^cabinet/requests/(?P<iid>\d+)/scr$', issue.IssueScoringView.as_view(), name='issue_scoring'),
    url(r'^cabinet/requests/(?P<iid>\d+)/rsr$', issue.IssueRemoteSurveyView.as_view(), name='issue_remote_survey'),
    url(r'^cabinet/requests/(?P<iid>\d+)/radr$', issue.IssueRemoteAdditionalDocumentsRequests.as_view(), name='issue_remote_add_docs_requests'),
    url(r'^cabinet/requests/(?P<iid>\d+)/rsd$', issue.IssueRemoteSignView.as_view(), name='issue_remote_for_sign'),
    url(r'^cabinet/requests/(?P<iid>\d+)/rsd/sign-file$', issue.IssueRemoteDocumentSignView.as_view(), name='issue_remote_file_sign'),
    url(r'^cabinet/requests/(?P<iid>\d+)/adr/clr$', issue.IssueAdditionalDocumentsRequestView.as_view(), name='issue_additional_documents_request_new'),
    url(r'^cabinet/requests/(?P<iid>\d+)/adr/(?P<adrid>\d+)$', issue.IssueAdditionalDocumentsRequestView.as_view(), name='issue_additional_documents_request'),
    url(r'^cabinet/requests/(?P<iid>\d+)/adr$', issue.IssueAdditionalDocumentsRequestsView.as_view(), name='issue_additional_documents_requests'),
    url(r'^cabinet/requests/(?P<iid>\d+)/adr/sign-file$', issue.IssueAdditionalDocumentSignView.as_view(), name='issue_adr_file_sign'),
    url(r'^cabinet/requests/(?P<iid>\d+)/finished$', issue.IssueFinishedView.as_view(), name='issue_finished'),
    url(r'^cabinet/requests/(?P<iid>\d+)/cancelled$', issue.IssueCancelledView.as_view(), name='issue_cancelled'),
    url(r'^cabinet/requests/(?P<iid>\d+)/chat', issue.IssueChatView.as_view(), name='issue_chat'),

    url(r'^rest/tender$', rest.TenderDataView.as_view(), name='rest_tender'),
    url(r'^rest/bank_commission$', csrf_exempt(rest.IssueBankCommissionView.as_view()), name='rest_bank_commission'),

    url(r'^rest/issues$', rest.IssuesView.as_view(), name='rest_issues'),
    url(r'^rest/issue/(?P<iid>\d+)$', rest.IssueView.as_view(), name='rest_issue'),
    url(r'^rest/issue/(?P<iid>\d+)/sec-dep-mgmt$', rest.IssueSecDepView.as_view(), name='rest_issue_sec_dep_mgmt'),
    url(r'^rest/issue/(?P<iid>\d+)/doc-ops-mgmt$', rest.IssueDocOpsView.as_view(), name='rest_issue_doc_ops_mgmt'),
    url(r'^rest/issue/(?P<iid>\d+)/lawyers-dep-mgmt$', rest.IssueLawyersDepView.as_view(), name='rest_issue_lawyers_dep_mgmt'),
    url(r'^rest/issue/(?P<iid>\d+)/generate_doc_ops_mgmt_conclusion_doc$', rest.IssueGenerateDocOpsView.as_view(), name='rest_generate_doc_ops_mgmt_conclusion_doc'),
    url(r'^rest/issue/(?P<iid>\d+)/generate_lawyers_dep_conclusion_doc$', rest.IssueGenerateLawyersDepConclusionDocView.as_view(), name='rest_generate_lawyers_dep_conclusion_doc'),
    url(r'^rest/issue/(?P<iid>\d+)/generate_sec-dep-mgmt$', rest.IssueGenerateSecDepMgmtView.as_view(), name='rest_generate_sec-dep-mgmt'),
    url(r'^rest/issue/(?P<iid>\d+)/messages$', rest.IssueMessagesView.as_view(), name='rest_issue_messages'),
    url(r'^rest/profile$', rest.ProfileView.as_view(), name='rest_profile'),

    url(r'^issue/(?P<iid>\d+)/docs-zip/$', rest.DocsZipView.as_view(), name='docs_zip'),
    url(r'^delete-docs/issue/(?P<iid>\d+)$', process_docs.IssueDeleteDocument.as_view(), name='delete_document'),
    url(r'^replace-docs/issue/(?P<iid>\d+)$', process_docs.IssueReplaceDocument.as_view(), name='replace_document'),
    url(r'^reform-docs/issue/(?P<iid>\d+)$', process_docs.IssueReformDocument.as_view(), name='reform_document'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('marer.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

marer/models/issue.py
import json
import warnings
import os
from copy import deepcopy

import feedparser
import requests
from dateutil.relativedelta import relativedelta
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.utils.formats import number_format
from django.utils.functional import cached_property
from django.utils.timezone import now

from marer import consts
from marer.models.base import Document, set_obj_update_time, FormOwnership
from marer.models.finance_org import FinanceOrgProductProposeDocument
from marer.models.issuer import Issuer, IssuerDocument
from marer.products import get_urgency_hours, get_urgency_days, get_finance_products_as_choices, FinanceProduct, get_finance_products, BankGuaranteeProduct
from marer.utils import CustomJSONEncoder, kontur
from marer.utils.issue import calculate_bank_commission, sum_str_format, generate_bg_number, issue_term_in_months, \
    calculate_effective_rate, CalculateUnderwritingCriteria
from marer.utils.morph import MorpherApi
from marer.utils.other import OKOPF_CATALOG, get_tender_info, are_docx_files_identical
from marer.utils.datetime_utils import today, month_difference_from_today


__all__ = [
    'Issue', 'IssueDocument', 'IssueClarification', 'IssueMessagesProxy',
    'IssueClarificationMessage', 'IssueFinanceOrgProposeClarificationMessageDocument'
]


class Issue(models.Model):
    class Meta:
        verbose_name = 'заявка'
        verbose_name_plural = 'заявки'
        ordering = ('-id',)

    product = models.CharField(verbose_name='банковский продукт', max_length=32, blank=False, null=False, choices=get_finance_products_as_choices())
    status = models.CharField(verbose_name='статус заявки', max_length=32, blank=False, null=False, choices=[
        (consts.ISSUE_STATUS_REGISTERING, 'Оформление заявки'),
        (consts.ISSUE_STATUS_REVIEW, 'Рассмотрение заявки'),
        (consts.ISSUE_STATUS_FINISHED, 'Завершена'),
        (consts.ISSUE_STATUS_CANCELLED, 'Отменена'),
        # (consts.ISSUE_STATUS_CLIENT_REVISION, 'Отправлено клиенту на доработку'),
        # (consts.ISSUE_STATUS_RETURNED_FROM_REVISION, 'Возвращена с доработки'),
        # (consts.ISSUE_STATUS_CLIENT_AGGREEMENT, 'Отправлено на согласование клиенту'),
        # (consts.ISSUE_STATUS_CANCELLED_BY_CLIENT, 'Отменена клиентом'),
    ], default=consts.ISSUE_STATUS_REGISTERING)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='пользователь', on_delete=models.DO_NOTHING, null=False)
    manager = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='менеджер по заявке',
        on_delete=models.DO_NOTHING,
        blank=True,
        null=True,
        related_name='managed_issues'
    )

    comment = models.TextField(verbose_name='комментарий к заявке', blank=True, null=False, default='')
    private_comment = models.TextField(verbose_name='приватный комментарий к заявке', blank=True, null=False, default='')
    updated_at = models.DateTimeField(verbose_name='время обновления', auto_now=True, null=False)
    created_at = models.DateTimeField(verbose_name='время создания', auto_now_add=True, null=False)

    issuer = models.ForeignKey(Issuer, on_delete=models.SET_NULL, blank=True, null=True)
    issuer_inn = models.CharField(verbose_name='ИНН заявителя', max_length=32, blank=True, null=False, default='')
    issuer_kpp = models.CharField(verbose_name='КПП заявителя', max_length=32, blank=True, null=False, default='')
    issuer_ogrn = models.CharField(verbose_name='ОГРН заявителя', max_length=32, blank=True, null=False, default='')
    issuer_full_name = models.CharField(verbose_name='полное наименование заявителя', max_length=512, blank=True, null=False, default='')
    issuer_short_name = models.CharField(verbose_name='краткое наименование заявителя', max_length=512, blank=True, null=False, default='')

    issuer_foreign_name = models.CharField(verbose_name='наименование заявителя на иностранном', max_length=512, blank=True, null=False, default='')
    issuer_legal_address = models.CharField(verbose_name='юридическй адрес заявителя', max_length=512, blank=True, null=False, default='')
    issuer_fact_address = models.CharField(verbose_name='фактический адрес заявителя', max_length=512, blank=True, null=False, default='')
    issuer_okpo = models.CharField(verbose_name='код ОКПО заявителя', max_length=32, blank=True, null=False, default='')
    issuer_okato = models.CharField(verbose_name='код ОКАТО заявителя', max_length=32, blank=True, null=False, default='')
    issuer_oktmo = models.CharField(verbose_name='код ОКТМО заявителя', max_length=32, blank=True, null=False, default='')
    issuer_registration_date = models.DateField(verbose_name='дата регистрации', blank=True, null=True)
    issuer_ifns_reg_date = models.DateField(verbose_name='дата постановки на учет в ИФНС', blank=True, null=True)
    issuer_ifns_reg_cert_number = models.CharField(verbose_name='номер свидетельства о постановке на учет ИФНС', max_length=32, blank=True, null=False, default='')
    issuer_okopf = models.CharField(verbose_name='код ОКОПФ (правовая форма) заявителя', max_length=32, blank=True, null=False, default='')
    issuer_okved = models.CharField(verbose_name='код ОКВЭД (основное направление деятельности) заявителя', max_length=32, blank=True, null=False, default='')

    issuer_head_first_name = models.CharField(verbose_name='имя руководителя', max_length=512, blank=True, null=False, default='')
    issuer_head_last_name = models.CharField(verbose_name='фамилия руководителя', max_length=512, blank=True, null=False, default='')
    issuer_head_middle_name = models.CharField(verbose_name='отчество руководителя', max_length=512, blank=True, null=False, default='')
    issuer_head_birthday = models.DateField(verbose_name='дата рождения руководителя', blank=True, null=True)
    issuer_head_org_position_and_permissions = models.CharField(verbose_name='должность, полномочия руководителя', max_length=512, blank=True, null=False, default='')
    issuer_head_phone = models.CharField(verbose_name='телефон руководителя', max_length=512, blank=True, null=False, default='')
    issuer_head_passport_series = models.CharField(verbose_name='серия паспорта руководителя', max_length=32, blank=True, null=False, default='')
    issuer_head_passport_number = models.CharField(verbose_name='номер паспорта руководителя', max_length=32, blank=True, null=False, default='')
    issuer_head_passport_issue_date = models.DateField(verbose_name='дата выдачи паспорта руководителя', blank=True, null=True)
    issuer_head_passport_issued_by = models.CharField(verbose_name='кем выдан паспорт руководителя', max_length=512, blank=True, null=False, default='')
    issuer_head_residence_address = models.CharField(verbose_name='адрес прописки руководителя', max_length=512, blank=True, null=False, default='')
    issuer_head_education_level = models.CharField(verbose_name='образование руководителя', max_length=512, blank=True, null=False, default='')
    issuer_head_org_work_experience = models.CharField(verbose_name='стаж работы руководителя в компании', max_length=512, blank=True, null=False, default='')
    issuer_head_share_in_authorized_capital = models.CharField(verbose_name='доля руководителя в уставном капиталле', max_length=512, blank=True, null=False, default='')
    issuer_head_industry_work_experience = models.CharField(verbose_name='опыт работы руководителя в отрасли', max_length=512, blank=True, null=False, default='')
    issuer_prev_org_info = models.CharField(verbose_name='предыдущее место работы руководителя, отрасль, должность', max_length=512, blank=True, null=False, default='')

    tender_gos_number = models.CharField(verbose_name='госномер или ссылка на тендер', max_length=512, blank=True, null=False, default='')
    tender_placement_type = models.CharField(verbose_name='способ определения поставщика в тендере', max_length=512, blank=True, null=False, default='')
    tender_exec_law = models.CharField(verbose_name='вид банковской гарантии', max_length=32, blank=True, null=True, choices=[
        (consts.TENDER_EXEC_LAW_44_FZ, '44-ФЗ'),
        (consts.TENDER_EXEC_LAW_223_FZ, '223-ФЗ'),
        (consts.TENDER_EXEC_LAW_185_FZ, '185-ФЗ'),
        (consts.TENDER_EXEC_LAW_COMMERCIAL, 'Коммерческий'),
        (consts.TENDER_EXEC_LAW_CUSTOMS, 'Таможенная'),
        (consts.TENDER_EXEC_LAW_VAT, 'Возврат НДС'),
    ])
    tender_publish_date = models.DateField(verbose_name='дата публикации тендера', blank=True, null=True)
    tender_start_cost = models.DecimalField(verbose_name='начальная цена тендера', max_digits=32, decimal_places=2, blank=False, null=False, default=0)
    tender_final_cost = models.DecimalField(verbose_name='конечная цена тендера', max_digits=32, decimal_places=2, blank=False, null=False, default=0)

    tender_contract_type = models.CharField(verbose_name='вид работ в тендере', max_length=32, blank=True, null=True, choices=[
        (consts.TENDER_CONTRACT_TYPE_SUPPLY_CONTRACT, 'Поставка товара'),
        (consts.TENDER_CONTRACT_TYPE_SERVICE_CONTRACT, 'Оказание услуг'),
        (consts.TENDER_CONTRACT_TYPE_WORKS_CONTRACT, 'Выполнение работ'),
    ])
    tender_has_prepayment = models.NullBooleanField(verbose_name='авансирование в тендере', blank=True, null=True)

    tender_responsible_full_name = models.CharField(verbose_name='полное наименование организатора тендера', max_length=512, blank=True, null=False, default='')
    tender_responsible_legal_address = models.CharField(verbose_name='юридический адрес организатора тендера', max_length=512, blank=True, null=False, default='')
    tender_responsible_inn = models.CharField(verbose_name='ИНН организатора тендера', max_length=32, blank=True, null=False, default='')

marer/forms/widgets.py
import copy
from django.forms.widgets import Select, ChoiceWidget, ClearableFileInput


class CallableChoicesSelect(Select):
    choices_maybe_callable = None

    def __init__(self, attrs=None, choices=()):
        super(ChoiceWidget, self).__init__(attrs)
        self.choices_maybe_callable = choices

    @property
    def choices(self):
        if callable(self.choices_maybe_callable):
            return self.choices_maybe_callable()
        else:
            return self.choices_maybe_callable

    def __deepcopy__(self, memo):
        obj = copy.copy(self)
        obj.attrs = self.attrs.copy()
        obj.choices_maybe_callable = copy.copy(self.choices_maybe_callable)
        memo[id(self)] = obj
        return obj


class ReadOnlyFileInput(ClearableFileInput):
    template_name = 'django/forms/widgets/read_only_file_input.html'
    initial_text = 'Скачать'
    input_text = 'Загрузить'

marer/views/mixins.py
from django.views.generic.base import ContextMixin

marer/views/static.py
from bakery.views import BuildableTemplateView


class Error404View(BuildableTemplateView):
    build_path = '404.html'
    template_name = 'marer/static/error_404.html'


class Error500View(BuildableTemplateView):
    build_path = '500.html'
    template_name = 'marer/static/error_500.html'

marer/templates/marer/cabinet/layout_dashboard.html
{% extends 'marer/cabinet/layout.html' %}
{% load staticfiles %}
{% block cabinet_content %}
    <div class="container container-bgnd">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <div class="list-group">
                    <a href="{% url 'cabinet_requests' %}" class="list-group-item{% if request.resolver_match.url_name == 'cabinet_requests' %} active{% endif %}">Заявки</a>
                    <a href="{% url 'cabinet_organizations' %}" class="list-group-item{% if request.resolver_match.url_name == 'cabinet_organizations' %} active{% endif %}">Организации</a>
                    <a href="{% url 'cabinet_profile' %}" class="list-group-item{% if request.resolver_match.url_name == 'cabinet_profile' %} active{% endif %}">Профиль</a>
                </div>
            </div>

            <div class="col-sm-9 col-md-10">
                {% block cabinet_dashboard_content %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

marer/templates/marer/cabinet/manager.html
{% extends 'marer/layout.html' %}

{% load staticfiles %}

{% block head_additional %}
    <link href="{% static 'jquery-ui/themes/base/jquery-ui.min.css' %}" rel="stylesheet">
    <link href="{% static '/marer/css/sticky-navbar.css' %}" rel="stylesheet">
    <link href="{% static '/marer/css/sticky-footer.css' %}" rel="stylesheet">
    <link href="{% static '/marer/css/btn-yellow.css' %}" rel="stylesheet">
    <link href="{% static '/marer/css/body-bgnd.css' %}" rel="stylesheet">
    <link href="{% static '/vue-cabinet/dist/static/css/app.css' %}" rel=stylesheet>
    <link href="{% static '/marer/css/suggestions.css' %}" rel="stylesheet">
    <link href="{% static '/marer/css/helpers.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div id="app"></div>
    {% include 'marer/footer.html' %}
    {% include 'marer/boostrap_js_body_part.html' %}

    <script type=text/javascript src="{% static 'vue-cabinet/dist/static/js/manifest.js' %}"></script>
    <script type=text/javascript src="{% static 'vue-cabinet/dist/static/js/vendor.js' %}"></script>
    <script type=text/javascript src="{% static 'marer/js/common.js' %}"></script>
    <script type=text/javascript src="{% static 'marer/js/form-submit-on-enter.js' %}"></script>
    <script type=text/javascript src="{% static 'vue-cabinet/dist/static/js/app.js' %}"></script>
    {% block js %}{% endblock %}

{% endblock %}

marer/templates/marer/cabinet/organizations.html
{% extends 'marer/cabinet/layout_dashboard.html' %}

{% block cabinet_dashboard_content %}
<div class="panel panel-info">
    <table class="table">
        <tr class="bg-info">
            <th>Название</th>
            <th>ИНН</th>
            <th>КПП</th>
            <th>ОГРН</th>
            <th></th>
        </tr>
        {% for issuer in issuers %}
            <tr>
                <td>{{ issuer.get_name }}</td>
                <td>{{ issuer.inn }}</td>
                <td>{{ issuer.kpp }}</td>
                <td>{{ issuer.ogrn }}</td>
                <td>
                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="iid" value="{{ issuer.id }}"/>
                        <button type="submit" class="btn btn-link btn-xs">
                            <span class="glyphicon glyphicon-remove text-danger"></span>
                        </button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

marer/templates/marer/cabinet/requests.html
{% extends 'marer/cabinet/layout_dashboard.html' %}
{% load marer_cabinet %}
{% load staticfiles %}
{% block cabinet_dashboard_content %}
    <div class="pull-right">
        &nbsp;
        &nbsp;
        <div class="btn-group" role="group" aria-label="Статус заявки">
            <a class="btn btn-yellow" href="{% url 'issue_new' %}" role="button">Создать заявку</a>
        </div>
    </div>
    <div class="pull-right">
        <form class="form-inline">
            <div class="form-group">
                <label>{{ filter_form.status.label }}</label>
                {{ filter_form.status }}
            </div>
        </form>
    </div>
<div class="clearfix"></div>
<br/>

<div class="panel panel-info">
    <table class="table">
        <tr class="bg-info">
            <th>
                <div class="row">
                <div class="col-md-7">
                    <a href="?order_by">Номер</a>
                </div>
                <div class="col-md-3">
                    <small><a href="?order_by=-id"><p class="glyphicon glyphicon-arrow-up fs-10"></p></a></small>
                    <small><a href="?order_by=id"><p class="glyphicon glyphicon-arrow-down fs-10"></p></a></small>
                </div>
                </div>
            </th>
            <th>
                <div class="row">
                <div class="col-md-9">
                    <a href="?order_by">Дата заведения заявки</a>
                </div>
                <div class="col-md-3">
                    <small><a href="?order_by=-created_at"><p class="glyphicon glyphicon-arrow-up fs-10"></p></a></small>
                    <small><a href="?order_by=created_at"><p class="glyphicon glyphicon-arrow-down fs-10"></p></a></small>
                </div>
                </div>
            </th>
            <th>
                <div class="row">
                <div class="col-md-9">
                    <a href="?order_by">Организация</a>
                </div>
                <div class="col-md-3">
                    <small><a href="?order_by=-issuer_full_name"><p class="glyphicon glyphicon-arrow-up fs-10"></p></a></small>
                    <small><a href="?order_by=issuer_full_name"><p class="glyphicon glyphicon-arrow-down fs-10"></p></a></small>
                </div>
                </div>
            </th>
            <th>
                <div class="row">
                <div class="col-md-7">
                    <a href="?order_by">Сумма</a>
                </div>
                <div class="col-md-3">
                    <small><a href="?order_by=-bg_sum"><p class="glyphicon glyphicon-arrow-up fs-10"></p></a></small>
                    <small><a href="?order_by=bg_sum"><p class="glyphicon glyphicon-arrow-down fs-10"></p></a></small>
                </div>
                </div>
            </th>
            <th>
                <div class="row">
                <div class="col-md-9">
                    <a href="?order_by">Статус</a>
                </div>
                <div class="col-md-3">
                    <small><a href="?order_by=-status"><p class="glyphicon glyphicon-arrow-up fs-10"></p></a></small>
                    <small><a href="?order_by=status"><p class="glyphicon glyphicon-arrow-down fs-10"></p></a></small>
                </div>
                </div>
            </th>
            <th>
                <div class="row">
                <div class="col-md-7">
                    <a href="?order_by">Последний комментарий</a>
                </div>
                <div class="col-md-3">
                    <small><a href="?order_by=-comment"><p class="glyphicon glyphicon-arrow-up fs-10"></p></a></small>
                    <small><a href="?order_by=comment"><p class="glyphicon glyphicon-arrow-down fs-10"></p></a></small>
                </div>
                </div>
            </th>
            <th><span class="glyphicon glyphicon-time"></span></th>
            <th></th>
        </tr>

        {% for issue in issues %}
            {% if issue.humanized_status == 'Оформление заявки' %}
                <tr class="bg-warning">
            {% elif issue.humanized_status == 'Завершена' %}
                <tr class="bg-success">
            {% elif issue.humanized_status == 'Отменена' %}
                <tr class="bg-danger">
            {% else %}
                <tr>
            {% endif %}
            <td>
                <a href="{% url 'cabinet_request' issue.id %}">{{ issue.humanized_id }}</a>
            </td>
                <td>{{ issue.created_at }}</td>
                <td>{{ issue.get_issuer_name }}</td>
                <td>{{ issue.humanized_sum }}</td>
                <td>{{ issue.humanized_status }}</td>
                <td>{% get_last_comment issue request.user %}</td>
                <td>{% get_urgency issue request.user %}</td>
                <td>
                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="issue_del" value="true" />
                        <input type="hidden" name="id" value="{{ issue.id }}"/>
                        <button type="submit" class="btn btn-link btn-xs pull-right">
                            <span class="text-danger">Удалить</span>
                        </button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </table>
</div>

{% if issues.has_other_pages %}
    <nav aria-label="Page navigation" class="text-center">
        <ul class="pagination">
            {% if issues.has_previous %}
                <li>
                    {% if issues.contacts.previous_page_number == 1 %}
                        <a href="{% url 'cabinet_requests' %}{{ get_params_as_new }}" aria-label="Previous">
                            <span aria-hidden="true" class="glyphicon glyphicon glyphicon-chevron-left"></span>
                        </a>
                    {% else %}
                        <a href="{% url 'cabinet_requests' %}?page={{ issues.previous_page_number }}{{ get_params_as_addition }}" aria-label="Previous">
                            <span aria-hidden="true" class="glyphicon glyphicon glyphicon-chevron-left"></span>
                        </a>
                    {% endif %}
                </li>
            {% else %}
                <li class="disabled">
                    <span aria-hidden="true" class="glyphicon glyphicon glyphicon-chevron-left"></span>
                </li>
            {% endif %}
            {% for pagenum in issues.paginator.page_range %}
                <li {% if issues.number == pagenum %}class="active"{% endif %}>
                    <a
                            {% if pagenum == 1 %}
                                href="{% url 'cabinet_requests' %}{{ get_params_as_new }}"
                            {% else %}
                                href="{% url 'cabinet_requests' %}?page={{ pagenum }}{{ get_params_as_addition }}"
                            {% endif %}
                    >{{ pagenum }}</a>
                </li>
            {% endfor %}
            {% if issues.has_next %}
                <li>
                    <a href="{% url 'cabinet_requests' %}?page={{ issues.next_page_number }}{{ get_params_as_addition }}" aria-label="Next">
                        <span aria-hidden="true" class="glyphicon glyphicon glyphicon-chevron-right"></span>
                    </a>
                </li>
            {% else %}
                <li class="disabled">
                    <span aria-hidden="true" class="glyphicon glyphicon glyphicon-chevron-right"></span>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}
{% endblock %}

{% block js %}
    <script>
        $(function () {
            $('body').on('change', '#id_status', function (e) {
                $(this).closest('form').submit();
            })
        });
    </script>

{% endblock %}